

const ENTITY_DATA = {
    // Resources
    tree: {
        category: "resource",
        type: "multiple",
        repositionedX: 0,
        repositionedY: -16,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 32,
        maxHP: 1,
        drops: [
            "wood",
            "wood",
        ],
    },
    bush: {
        category: "resource",
        type: "single",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
        maxHP: 1,
        drops: [
            "fiber",
        ],
    },
    rock: {
        category: "resource",
        type: "single",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
        maxHP: 1,
        drops: [
            "stone",
            "stone",
        ]
    },
    // Items - materials
    wood: {
        category: "item",
        type: "material",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    fiber: {
        category: "item",
        type: "material",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    stone: {
        category: "item",
        type: "material",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    // Item - weapon
    sword: {
        category: "weapon",
        type: "sword",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    // Item - tool
    hoe: {
        category: "tool",
        type: "hoe",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    axe: {
        category: "tool",
        type: "axe",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    pickaxe: {
        category: "tool",
        type: "pickaxe",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    }, 
    "potato_seed": {
        category: "item",
        type: "seed",
        repositionedX: 0,
        repositionedY: -16,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 32,
        crop_grow: "potato_grow",
    },
    "potato_grow": {
        repositionedX: 0,
        repositionedY: -16,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 32,
    }
}

export {
    ENTITY_DATA,
}