

const ENTITY_DATA = {
    // tree: {
    //     type: "resource",
    //     repositionedX: 0,
    //     repositionedY: -16,
    //     width: 20,
    //     height: 20,
    //     offsetX: 6,
    //     offsetY: 38,
    //     hasSecondPart: true,
    // },
    // bush: {
    //     type: "resource",
    //     repositionedX: 0,
    //     repositionedY: 0,
    //     width: 20,
    //     height: 20,
    //     offsetX: 6,
    //     offsetY: 6,
    // },
    // rock: {
    //     type: "resource",
    //     repositionedX: 0,
    //     repositionedY: 0,
    //     width: 20,
    //     height: 20,
    //     offsetX: 6,
    //     offsetY: 6,
    // },
    tree: {
        type: "resource",
        repositionedX: 0,
        repositionedY: -16,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 32,
        hasSecondPart: true,
        maxHP: 1,
        drops: [
            "wood",
            "wood",
        ],
    },
    bush: {
        type: "resource",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
        maxHP: 1,
        drops: [
            "fiber",
        ],
    },
    rock: {
        type: "resource",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
        maxHP: 1,
        drops: [
            "stone",
            "stone",
        ]
    },
    wood: {
        type: "item",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    fiber: {
        type: "item",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
    stone: {
        type: "item",
        repositionedX: 0,
        repositionedY: 0,
        width: 32,
        height: 32,
        offsetX: 0,
        offsetY: 0,
    },
}

export {
    ENTITY_DATA,
}